- name: Lighthouse CI Action
  # You may pin to the exact commit or the version.
  # uses: treosh/lighthouse-ci-action@3f01a66925eae1613cb01504ae14ddb29b76cf0d
  uses: treosh/lighthouse-ci-action@v3
  with:
    # List of URL(s) to analyze
    urls: # optional
    # Path to a Lighthouse budgets.json file
    budgetPath: # optional
    # Path to a LHCI lighthouserc.json file
    configPath: # optional
    # Opt-out of saving Lighthouse results as an action artifacts
    uploadArtifacts: # optional
    # 
    temporaryPublicStorage: # optional
    # Number of runs to do per URL
    runs: # optional
    # Address of a LHCI server
    serverBaseUrl: # optional
    # API token to push to LHCI server
    serverToken: # optional
    # Basic auth username for LHCI server
    basicAuthUsername: # optional
    # Basic auth password for LHCI server
    basicAuthPassword: # optional
